# Generated by Django 3.1.5 on 2021-01-18 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('spotify_id', models.CharField(max_length=22)),
                ('picture_url', models.URLField(blank=True)),
                ('album_type', models.CharField(choices=[('album', 'Album'), ('single', 'Single'), ('compilation', 'Compilation')], max_length=11)),
                ('genres', models.JSONField()),
                ('release_date', models.DateField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('spotify_id', models.CharField(max_length=22)),
                ('picture_url', models.URLField(blank=True)),
                ('genres', models.JSONField()),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('spotify_id', models.CharField(max_length=22)),
                ('picture_url', models.URLField(blank=True)),
                ('explicit', models.BooleanField(default=False)),
                ('disc_number', models.PositiveSmallIntegerField(default=1)),
                ('track_number', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField(verbose_name='duration in milliseconds')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spots.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.artist')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
