# Generated by Django 3.1.5 on 2021-01-19 05:40

from django.db import migrations, models
import spots.models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_auto_20210118_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('album', 'Album'), ('single', 'Single'), ('compilation', 'Compilation')], error_messages={'blank': 'Album type must be specified.'}, max_length=11),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(error_messages={'blank': 'Spot name is required.', 'max_length': 'Spot name cannot exceed 50 characters.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, validators=[spots.models.validate_release_date_not_in_future]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(error_messages={'blank': 'Spot name is required.', 'max_length': 'Spot name cannot exceed 50 characters.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(error_messages={'blank': 'Spot name is required.', 'max_length': 'Spot name cannot exceed 50 characters.'}, max_length=50),
        ),
    ]
